### ISSUE TITLE
1.0.0?

### ISSUE THREAD

**Issue by phated** [micromatch/is-valid-glob#4]
This module looks really stable.  Can it be bumped to 1.0.0?

**Comment by phated** [comment]
@jonschlinkert I'm noticing that this needs your updaters run against it. Can you or @doowb run them and I can finish up the release?

**Comment by jonschlinkert** [comment]
done. I just pushed up

**Comment by jonschlinkert** [comment]
looks like this is done!

**Comment by phated** [comment]
Just needs to be published once the CI finishes.  I'll post once I've done that.

**Comment by jonschlinkert** [comment]
I just made sure you're added on npm if you want to go ahead and publish

**Comment by phated** [comment]
This has been published.
